export const weatherCodes = {
    0: "Klart",
    1: "Framför allt klart",
    2: "Delvis molnigt",
    3: "Mulet",
    45: "Dimma",
    48: "Rimfrostdimma",
    51: "Lätt duggregn",
    53: "Måttligt duggregn",
    55: "Tätt duggregn",
    56: "Lätt frysdugg",
    57: "Tät frysdugg",
    61: "Lätt regn",
    63: "Måttligt regn",
    65: "Kraftigt regn",
    66: "Lätt frysregn",
    67: "Kraftigt frysregn",
    71: "Lätt snöfall",
    73: "Måttligt snöfall",
    75: "Kraftigt snöfall",
    77: "Snöflingor",
    80: "Lätt regnskur",
    81: "Måttlig regnskur",
    82: "Kraftig regnskur",
    85: "Lätt snöskur",
    86: "Kraftig snöskur",
    95: "Åskväder (lätt eller måttligt)",
    96: "Åskväder med liten hagel",
    99: "Åskväder med kraftig hagel"
};