export const weatherCodes = {
    0: { description: "Klart", image: "images/sunny.jpg" },
    1: { description: "Framför allt klart", image: "images/sunny.jpg" },
    2: { description: "Delvis molnigt", image: "images/clouds.jpg" },
    3: { description: "Mulet", image: "images/clouds.jpg" },
    45: { description: "Dimma", image: "images/frost.jpg" },
    48: { description: "Rimfrostdimma", image: "images/frost.jpg" },
    51: { description: "Lätt duggregn", image: "images/raindrop.jpg" },
    53: { description: "Måttligt duggregn", image: "images/raindrop.jpg" },
    55: { description: "Tätt duggregn", image: "images/rain.jpg" },
    56: { description: "Lätt frysdugg", image: "images/frost.jpg" },
    57: { description: "Tät frysdugg", image: "images/frost.jpg" },
    61: { description: "Lätt regn", image: "images/rain.jpg" },
    63: { description: "Måttligt regn", image: "images/rain.jpg" },
    65: { description: "Kraftigt regn", image: "images/rain.jpg" },
    66: { description: "Lätt frysregn", image: "images/frost.jpg" },
    67: { description: "Kraftigt frysregn", image: "images/frost.jpg" },
    71: { description: "Lätt snöfall", image: "images/winter.jpg" },
    73: { description: "Måttligt snöfall", image: "images/winter.jpg" },
    75: { description: "Kraftigt snöfall", image: "images/winter.jpg" },
    77: { description: "Snöflingor", image: "images/winter.jpg" },
    80: { description: "Lätt regnskur", image: "images/raindrop.jpg" },
    81: { description: "Måttlig regnskur", image: "images/rain.jpg" },
    82: { description: "Kraftig regnskur", image: "images/rain.jpg" },
    85: { description: "Lätt snöskur", image: "images/winter.jpg" },
    86: { description: "Kraftig snöskur", image: "images/winter.jpg" },
    95: { description: "Åskväder (lätt eller måttligt)", image: "images/rain.jpg" },
    96: { description: "Åskväder med liten hagel", image: "images/rain.jpg" },
    99: { description: "Åskväder med kraftig hagel", image: "images/rain.jpg" }
};
